/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { InteractionUserWhereInput } from "./InteractionUserWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class InteractionUserupdateManyArgs {
  @ApiProperty({
    required: false,
    type: () => InteractionUserWhereInput,
  })
  @Field(() => InteractionUserWhereInput, { nullable: true })
  @Type(() => InteractionUserWhereInput)
  where?: InteractionUserWhereInput;
}

export { InteractionUserupdateManyArgs };
