/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { Logger } from "winston";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateInteractionUserArgs } from "./CreateInteractionUserArgs";
import { UpdateInteractionUserArgs } from "./UpdateInteractionUserArgs";
import { DeleteInteractionUserArgs } from "./DeleteInteractionUserArgs";
import { InteractionUserFindManyArgs } from "./InteractionUserFindManyArgs";
import { InteractionUserFindUniqueArgs } from "./InteractionUserFindUniqueArgs";
import { InteractionUser } from "./InteractionUser";
import { User } from "../../user/base/User";
import { InteractionUserService } from "../interactionUser.service";

@graphql.Resolver(() => InteractionUser)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class InteractionUserResolverBase {
  constructor(
    protected readonly service: InteractionUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "read",
    possession: "any",
  })
  async _interactionUsersMeta(
    @graphql.Args() args: InteractionUserFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [InteractionUser])
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "read",
    possession: "any",
  })
  async interactionUsers(
    @graphql.Args() args: InteractionUserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<InteractionUser>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "InteractionUser",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: InteractionUser) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => InteractionUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "read",
    possession: "own",
  })
  async interactionUser(
    @graphql.Args() args: InteractionUserFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<InteractionUser | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "InteractionUser",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => InteractionUser)
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "create",
    possession: "any",
  })
  async createInteractionUser(
    @graphql.Args() args: CreateInteractionUserArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<InteractionUser> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "InteractionUser",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"InteractionUser"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user2: args.data.user2
          ? {
              connect: args.data.user2,
            }
          : undefined,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => InteractionUser)
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "update",
    possession: "any",
  })
  async updateInteractionUser(
    @graphql.Args() args: UpdateInteractionUserArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<InteractionUser | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "InteractionUser",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"InteractionUser"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user2: args.data.user2
            ? {
                connect: args.data.user2,
              }
            : undefined,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => InteractionUser)
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "delete",
    possession: "any",
  })
  async deleteInteractionUser(
    @graphql.Args() args: DeleteInteractionUserArgs
  ): Promise<InteractionUser | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "read",
    possession: "any",
  })
  async user2(
    @graphql.Parent() parent: InteractionUser,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser2(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "InteractionUser",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: InteractionUser,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
