/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Inject } from "@nestjs/common";
import { Prisma, InteractionUser, User } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { Logger } from "winston";
import { DbService } from "src/dbService/db.service";

export class InteractionUserServiceBase {
  constructor(
    protected readonly prisma: DbService,
    @Inject("winston")
    protected readonly logger: Logger
  ) {}

  async count<T extends Prisma.InteractionUserFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserFindManyArgs>
  ): Promise<number> {
    return await this.prisma.interactionUser.count(args);
  }

  async findMany<T extends Prisma.InteractionUserFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserFindManyArgs>
  ): Promise<PaginatedInterface<InteractionUser>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.interactionUser.findMany(args),
      this.prisma.interactionUser.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.InteractionUserFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserFindUniqueArgs>
  ): Promise<InteractionUser | null> {
    return await this.prisma.interactionUser.findUnique(args);
  }
  async create<T extends Prisma.InteractionUserCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserCreateArgs>
  ): Promise<InteractionUser> {
    return await this.prisma.interactionUser.create<T>(args);
  }
  async createMany<T extends Prisma.InteractionUserCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.interactionUser.createMany<T>(args);
  }
  async update<T extends Prisma.InteractionUserUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserUpdateArgs>
  ): Promise<InteractionUser> {
    return await this.prisma.interactionUser.update<T>(args);
  }
  async delete<T extends Prisma.InteractionUserDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserDeleteArgs>
  ): Promise<InteractionUser> {
    return await this.prisma.interactionUser.delete(args);
  }

  async updateMany<T extends Prisma.InteractionUserUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InteractionUserUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.interactionUser.updateMany(args);
  }

  async getUser2(parentId: string): Promise<User | null> {
    return this.prisma.interactionUser
      .findUnique({
        where: { id: parentId },
      })
      .user2();
  }

  async getUsers(parentId: string): Promise<User | null> {
    return this.prisma.interactionUser
      .findUnique({
        where: { id: parentId },
      })
      .users();
  }
}
