/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnonceWhereInput } from "./AnnonceWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class AnnonceupdateManyArgs {
  @ApiProperty({
    required: false,
    type: () => AnnonceWhereInput,
  })
  @Field(() => AnnonceWhereInput, { nullable: true })
  @Type(() => AnnonceWhereInput)
  where?: AnnonceWhereInput;
}

export { AnnonceupdateManyArgs };
