/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { Logger } from "winston";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateAnnonceArgs } from "./CreateAnnonceArgs";
import { UpdateAnnonceArgs } from "./UpdateAnnonceArgs";
import { DeleteAnnonceArgs } from "./DeleteAnnonceArgs";
import { AnnonceFindManyArgs } from "./AnnonceFindManyArgs";
import { AnnonceFindUniqueArgs } from "./AnnonceFindUniqueArgs";
import { Annonce } from "./Annonce";
import { InteractionFindManyArgs } from "../../interaction/base/InteractionFindManyArgs";
import { Interaction } from "../../interaction/base/Interaction";
import { User } from "../../user/base/User";
import { AnnonceService } from "../annonce.service";

@graphql.Resolver(() => Annonce)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AnnonceResolverBase {
  constructor(
    protected readonly service: AnnonceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "read",
    possession: "any",
  })
  async _annoncesMeta(
    @graphql.Args() args: AnnonceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Annonce])
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "read",
    possession: "any",
  })
  async annonces(
    @graphql.Args() args: AnnonceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<Annonce>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Annonce",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: Annonce) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => Annonce, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "read",
    possession: "own",
  })
  async annonce(
    @graphql.Args() args: AnnonceFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Annonce | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Annonce",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Annonce)
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "create",
    possession: "any",
  })
  async createAnnonce(
    @graphql.Args() args: CreateAnnonceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Annonce> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Annonce",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Annonce"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Annonce)
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "update",
    possession: "any",
  })
  async updateAnnonce(
    @graphql.Args() args: UpdateAnnonceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Annonce | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Annonce",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Annonce"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Annonce)
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "delete",
    possession: "any",
  })
  async deleteAnnonce(
    @graphql.Args() args: DeleteAnnonceArgs
  ): Promise<Annonce | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Interaction])
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "read",
    possession: "any",
  })
  async interactions(
    @graphql.Parent() parent: Annonce,
    @graphql.Args() args: InteractionFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Interaction[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Interaction",
    });
    const results = await this.service.findInteractions(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Annonce",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: Annonce,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
