/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnonceWhereInput } from "./AnnonceWhereInput";
import { Type } from "class-transformer";
import { AnnonceOrderByInput } from "./AnnonceOrderByInput";

@ArgsType()
class AnnonceFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => AnnonceWhereInput,
  })
  @Field(() => AnnonceWhereInput, { nullable: true })
  @Type(() => AnnonceWhereInput)
  where?: AnnonceWhereInput;

  @ApiProperty({
    required: false,
    type: AnnonceOrderByInput,
  })
  @Field(() => AnnonceOrderByInput, { nullable: true })
  @Type(() => AnnonceOrderByInput)
  orderBy?: AnnonceOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { AnnonceFindManyArgs };
