/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumInteractionInteractionType } from "./EnumInteractionInteractionType";
import { User } from "../../user/base/User";
import { Annonce } from "../../annonce/base/Annonce";
@ObjectType()
class Interaction {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt!: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumInteractionInteractionType,
    isArray: true,
  })
  @IsEnum(EnumInteractionInteractionType, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumInteractionInteractionType], {
    nullable: true,
  })
  interactionType?: Array<"Like" | "Report" | "Comment">;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;

  @ApiProperty({
    required: false,
    type: () => Annonce,
  })
  @ValidateNested()
  @Type(() => Annonce)
  @IsOptional()
  annonce?: Annonce | null;
}
export { Interaction };
