/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { InteractionWhereInput } from "./InteractionWhereInput";
import { Type } from "class-transformer";
import { InteractionOrderByInput } from "./InteractionOrderByInput";

@ArgsType()
class InteractionFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => InteractionWhereInput,
  })
  @Field(() => InteractionWhereInput, { nullable: true })
  @Type(() => InteractionWhereInput)
  where?: InteractionWhereInput;

  @ApiProperty({
    required: false,
    type: InteractionOrderByInput,
  })
  @Field(() => InteractionOrderByInput, { nullable: true })
  @Type(() => InteractionOrderByInput)
  orderBy?: InteractionOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { InteractionFindManyArgs };
