/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { InteractionWhereUniqueInput } from "./InteractionWhereUniqueInput";
import { InteractionUpdateInput } from "./InteractionUpdateInput";

@ArgsType()
class UpdateInteractionArgs {
  @Field(() => InteractionWhereUniqueInput, { nullable: false })
  where!: InteractionWhereUniqueInput;
  @Field(() => InteractionUpdateInput, { nullable: false })
  data!: InteractionUpdateInput;
}

export { UpdateInteractionArgs };
