export const INVALID_USERNAME_ERROR = "INVALID_USERNAME_ERROR";
export const INVALID_PASSWORD_ERROR = "INVALID_PASSWORD_ERROR";
export const INVALID_ROLE_ERROR = "INVALID_ROLE_ERROR";
export const INVALID_FIRSTNAME_ERROR = "INVALID_FIRSTNAME_ERROR";
export const INVALID_LASTNAME_ERROR = "INVALID_LASTNAME_ERROR";
export const INVALID_EMAIL_ERROR = "INVALID_EMAIL_ERROR";
export const INVALID_ID_ERROR = "INVALID_ID_ERROR";
